kind: pipeline
type: kubernetes
name: default

steps:
- name: Make-zip
  image: python:3.8-alpine
  commands:
  - pip install pipenv
  - pipenv lock -r > requirements.txt
  - pip install --target ./package -r requirements.txt
  - rm requirements.txt
  - cp bot.py ./package
  - apk add --no-cache zip
  - cd package && zip -r ../lambda.zip * && cd ..
  - rm -rf package

# - name: Terraform-Apply
#   image: hashicorp/terraform:0.14.3
#   commands:
#   - cd terraform
#   - terraform init
#   - terraform apply -auto-approve
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: aws_access_key_id
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: aws_secret_access_key
#     AWS_DEFAULT_REGION: us-east-1
